-- Species, pet reports and their photos.

-- ============================================================
-- Species: a reference table instead of an enum, so adding one is an insert,
-- not a type migration that installed app builds can't decode. Reference data
-- every environment needs, so it lives here rather than in seed.sql.
-- ============================================================
create table public.species (
  id         smallint primary key,
  slug       text not null unique check (slug ~ '^[a-z_]{2,30}$'),
  label      text not null check (length(label) between 1 and 40),
  sort_order smallint not null default 0
);

alter table public.species enable row level security;
revoke all on public.species from anon, authenticated;
grant select on public.species to anon, authenticated;

create policy "species are readable by everyone"
  on public.species for select
  to anon, authenticated
  using (true);

insert into public.species (id, slug, label, sort_order) values
  (1, 'dog', 'Dog', 1),
  (2, 'cat', 'Cat', 2),
  (3, 'bird', 'Bird', 3),
  (4, 'rabbit', 'Rabbit', 4),
  (99, 'other', 'Other', 99);

-- ============================================================
-- Pet reports
--
-- Location privacy: "last seen" is often the owner's home, so the exact point
-- (`location`) is never granted to an API role. Everyone — the author
-- included — reads `location_public` / `public_lng` / `public_lat`, snapped to
-- a 0.001° grid (~100 m). Filtering also runs on the snapped point: querying
-- the exact one with ever-smaller boxes would let anyone binary-search it.
-- The exact point stays for server-side work (future nearby alerts).
--
-- Status is server-owned and only changes through the RPCs below and the
-- moderation functions:
--   active   -> reunited (owner), expired (cron), hidden (flags/moderator), removed (moderator)
--   expired  -> active (owner renews), reunited (owner)
--   hidden   -> active/expired (moderator restores), removed (moderator)
-- ============================================================
create table public.pet_reports (
  id              uuid primary key default gen_random_uuid(),
  created_by      uuid not null references public.profiles (id) on delete cascade,
  -- Generated by the client per submission so a retried request can't create
  -- a duplicate; unique per author, not globally.
  client_id       uuid not null,
  kind            text not null check (kind in ('lost', 'found')),
  status          text not null default 'active'
                    check (status in ('active', 'reunited', 'expired', 'hidden', 'removed')),
  species_id      smallint not null references public.species (id),
  pet_name        text check (length(trim(pet_name)) between 1 and 50),
  description     text not null check (length(trim(description)) between 1 and 1000),
  color           text check (length(trim(color)) between 1 and 40),
  size            text check (size in ('small', 'medium', 'large')),
  last_seen_at    timestamptz not null,
  location        extensions.geography(point, 4326) not null,
  location_public extensions.geography(point, 4326) generated always as
                    (extensions.st_snaptogrid(location::extensions.geometry, 0.001)::extensions.geography) stored,
  public_lng      double precision generated always as
                    (extensions.st_x(extensions.st_snaptogrid(location::extensions.geometry, 0.001))) stored,
  public_lat      double precision generated always as
                    (extensions.st_y(extensions.st_snaptogrid(location::extensions.geometry, 0.001))) stored,
  -- Trigger-maintained (see sightings), so a list never re-counts sightings.
  sighting_count  integer not null default 0 check (sighting_count >= 0),
  expires_at      timestamptz not null,
  resolved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (created_by, client_id)
);

-- The map query: active reports inside a box, newest first.
create index pet_reports_active_location_idx
  on public.pet_reports using gist (location_public)
  where status = 'active';
-- "My reports" (and the created_by foreign key; the unique index above leads
-- with created_by too, but this one also serves the sort).
create index pet_reports_created_by_idx on public.pet_reports (created_by, created_at desc);
create index pet_reports_species_id_idx on public.pet_reports (species_id);
-- The hourly expiry job.
create index pet_reports_active_expires_at_idx
  on public.pet_reports (expires_at)
  where status = 'active';

alter table public.pet_reports enable row level security;
revoke all on public.pet_reports from anon, authenticated;
-- Every column except the exact `location`. Clients must name their columns
-- (`select=*` is refused), which the adapters do anyway.
grant select (
  id, created_by, kind, status, species_id, pet_name, description, color, size,
  last_seen_at, location_public, public_lng, public_lat, sighting_count,
  expires_at, resolved_at, created_at, updated_at
) on public.pet_reports to anon, authenticated;
-- No insert/update/delete grants: writes go through the RPCs below.

create policy "open and reunited reports are public"
  on public.pet_reports for select
  to anon, authenticated
  using (status in ('active', 'reunited'));

create policy "authors see their own reports"
  on public.pet_reports for select
  to authenticated
  using (created_by = (select auth.uid()));

create policy "moderators see every report"
  on public.pet_reports for select
  to authenticated
  using ((select public.has_role('moderator')));

create trigger pet_reports_set_updated_at
  before update on public.pet_reports
  for each row execute function private.set_updated_at();

-- ============================================================
-- Report photos
--
-- Files live in the private `report-photos` bucket under
-- `{user_id}/{uuid}.jpg`; this table is what makes one visible (storage
-- policies in a later migration). Visibility follows the parent report: the
-- policy's subquery runs under pet_reports' own RLS.
-- ============================================================
create table public.report_photos (
  id           uuid primary key default gen_random_uuid(),
  report_id    uuid not null references public.pet_reports (id) on delete cascade,
  storage_path text not null unique check (length(storage_path) <= 200),
  position     smallint not null check (position between 0 and 4),
  created_at   timestamptz not null default now(),
  unique (report_id, position)
);

alter table public.report_photos enable row level security;
revoke all on public.report_photos from anon, authenticated;
grant select on public.report_photos to anon, authenticated;

create policy "photos are visible with their report"
  on public.report_photos for select
  to anon, authenticated
  using (exists (select 1 from public.pet_reports r where r.id = report_id));

-- ============================================================
-- Shared write helpers (private: not callable through the API)
-- ============================================================

-- The caller, or not_authenticated.
create function private.require_user()
returns uuid
language plpgsql
stable
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
begin
  if uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  return uid;
end;
$$;

-- Serializes one user's writes for the rest of the transaction, so two
-- concurrent requests can't both pass a rate-limit count.
create function private.lock_user(uid uuid)
returns void
language sql
set search_path = ''
as $$
  select pg_advisory_xact_lock(hashtextextended('user:' || uid::text, 0));
$$;

-- A photo path the caller may attach: their own folder, actually uploaded to
-- the bucket, and not already attached to something else.
create function private.assert_own_photo(uid uuid, path text)
returns void
language plpgsql
stable
set search_path = ''
as $$
begin
  if path is null
     or split_part(path, '/', 1) <> uid::text
     or not exists (
       select 1 from storage.objects o
       where o.bucket_id = 'report-photos' and o.name = path
     )
     or exists (select 1 from public.report_photos p where p.storage_path = path)
  then
    raise exception 'invalid_input' using errcode = '22023', detail = 'photo';
  end if;
end;
$$;

create function private.assert_point(lng double precision, lat double precision)
returns void
language plpgsql
immutable
set search_path = ''
as $$
begin
  if lng is null or lat is null or lng not between -180 and 180 or lat not between -90 and 90 then
    raise exception 'invalid_input' using errcode = '22023', detail = 'location';
  end if;
end;
$$;

revoke execute on function private.require_user() from public, anon, authenticated;
revoke execute on function private.lock_user(uuid) from public, anon, authenticated;
revoke execute on function private.assert_own_photo(uuid, text) from public, anon, authenticated;
revoke execute on function private.assert_point(double precision, double precision) from public, anon, authenticated;

-- ============================================================
-- create_report
--
-- Idempotent on (caller, client_id): a retry returns the report the first
-- attempt created. At most 5 new reports per user per hour.
-- ============================================================
create function public.create_report(
  p_client_id    uuid,
  p_kind         text,
  p_species_id   smallint,
  p_description  text,
  p_last_seen_at timestamptz,
  p_lng          double precision,
  p_lat          double precision,
  p_pet_name     text default null,
  p_color        text default null,
  p_size         text default null,
  p_photo_paths  text[] default '{}'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid       uuid := private.require_user();
  report_id uuid;
  path      text;
  idx       integer := 0;
begin
  perform private.lock_user(uid);

  select r.id into report_id
  from public.pet_reports r
  where r.created_by = uid and r.client_id = p_client_id;
  if found then
    return report_id;
  end if;

  if (select count(*) from public.pet_reports r
      where r.created_by = uid and r.created_at > now() - interval '1 hour') >= 5 then
    raise exception 'rate_limited' using errcode = 'P0001';
  end if;

  perform private.assert_point(p_lng, p_lat);
  if p_client_id is null
     or p_last_seen_at is null
     or p_last_seen_at > now() + interval '5 minutes'
     or p_last_seen_at < now() - interval '90 days'
     or coalesce(cardinality(p_photo_paths), 0) > 5
  then
    raise exception 'invalid_input' using errcode = '22023';
  end if;

  foreach path in array coalesce(p_photo_paths, '{}') loop
    perform private.assert_own_photo(uid, path);
  end loop;

  -- Column checks (kind, species, lengths) reject anything else with 23514/23503.
  insert into public.pet_reports (
    created_by, client_id, kind, species_id, pet_name, description, color, size,
    last_seen_at, location, expires_at
  ) values (
    uid, p_client_id, p_kind, p_species_id, nullif(trim(p_pet_name), ''), trim(p_description),
    nullif(trim(p_color), ''), p_size, p_last_seen_at,
    extensions.st_setsrid(extensions.st_makepoint(p_lng, p_lat), 4326)::extensions.geography,
    now() + interval '30 days'
  )
  returning id into report_id;

  foreach path in array coalesce(p_photo_paths, '{}') loop
    insert into public.report_photos (report_id, storage_path, position) values (report_id, path, idx);
    idx := idx + 1;
  end loop;

  return report_id;
end;
$$;

revoke execute on function public.create_report(uuid, text, smallint, text, timestamptz, double precision, double precision, text, text, text, text[]) from public, anon;
grant execute on function public.create_report(uuid, text, smallint, text, timestamptz, double precision, double precision, text, text, text, text[]) to authenticated;

-- Locks the caller's own report for a status change, or raises.
create function private.lock_own_report(uid uuid, p_report_id uuid)
returns public.pet_reports
language plpgsql
set search_path = ''
as $$
declare
  report public.pet_reports;
begin
  select * into report from public.pet_reports where id = p_report_id for update;
  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;
  if report.created_by <> uid then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  return report;
end;
$$;

revoke execute on function private.lock_own_report(uuid, uuid) from public, anon, authenticated;

-- The owner closes the report with a happy ending. Idempotent.
create function public.mark_reunited(p_report_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  report public.pet_reports := private.lock_own_report(private.require_user(), p_report_id);
begin
  if report.status = 'reunited' then
    return;
  end if;
  if report.status not in ('active', 'expired') then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  update public.pet_reports set status = 'reunited', resolved_at = now() where id = p_report_id;
end;
$$;

revoke execute on function public.mark_reunited(uuid) from public, anon;
grant execute on function public.mark_reunited(uuid) to authenticated;

-- The owner keeps an open or expired report up for another 30 days. A hidden
-- or removed report can't be renewed back into view.
create function public.renew_report(p_report_id uuid)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  report public.pet_reports := private.lock_own_report(private.require_user(), p_report_id);
  new_expiry timestamptz := now() + interval '30 days';
begin
  if report.status not in ('active', 'expired') then
    raise exception 'not_allowed' using errcode = '42501';
  end if;
  update public.pet_reports set status = 'active', expires_at = new_expiry where id = p_report_id;
  return new_expiry;
end;
$$;

revoke execute on function public.renew_report(uuid) from public, anon;
grant execute on function public.renew_report(uuid) to authenticated;

-- ============================================================
-- Map reads. security invoker: RLS and the column grants above apply, so
-- these can only return what the caller could select anyway. Bounded on the
-- server whatever the client asks for.
-- ============================================================
create function public.reports_in_bbox(
  min_lng     double precision,
  min_lat     double precision,
  max_lng     double precision,
  max_lat     double precision,
  kinds       text[] default null,
  species_ids smallint[] default null,
  max_rows    integer default 200
)
returns table (
  id             uuid,
  kind           text,
  species_id     smallint,
  pet_name       text,
  lng            double precision,
  lat            double precision,
  last_seen_at   timestamptz,
  sighting_count integer,
  cover_photo    text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    r.id, r.kind, r.species_id, r.pet_name, r.public_lng, r.public_lat,
    r.last_seen_at, r.sighting_count,
    (select p.storage_path from public.report_photos p where p.report_id = r.id and p.position = 0)
  from public.pet_reports r
  where r.status = 'active'
    and r.expires_at > now()
    and r.location_public operator(extensions.&&)
        extensions.st_makeenvelope(min_lng, min_lat, max_lng, max_lat, 4326)::extensions.geography
    and (kinds is null or r.kind = any (kinds))
    and (species_ids is null or r.species_id = any (species_ids))
  order by r.last_seen_at desc
  limit least(greatest(coalesce(max_rows, 200), 1), 500);
$$;

create function public.reports_near(
  origin_lng  double precision,
  origin_lat  double precision,
  radius_m    double precision default 5000,
  kinds       text[] default null,
  species_ids smallint[] default null,
  max_rows    integer default 50
)
returns table (
  id             uuid,
  kind           text,
  species_id     smallint,
  pet_name       text,
  lng            double precision,
  lat            double precision,
  distance_m     double precision,
  last_seen_at   timestamptz,
  sighting_count integer,
  cover_photo    text
)
language sql
stable
security invoker
set search_path = ''
as $$
  with origin as (
    select extensions.st_setsrid(extensions.st_makepoint(origin_lng, origin_lat), 4326)::extensions.geography as point
  )
  select
    r.id, r.kind, r.species_id, r.pet_name, r.public_lng, r.public_lat,
    extensions.st_distance(r.location_public, origin.point),
    r.last_seen_at, r.sighting_count,
    (select p.storage_path from public.report_photos p where p.report_id = r.id and p.position = 0)
  from public.pet_reports r, origin
  where r.status = 'active'
    and r.expires_at > now()
    and extensions.st_dwithin(r.location_public, origin.point, least(greatest(radius_m, 0), 50000))
    and (kinds is null or r.kind = any (kinds))
    and (species_ids is null or r.species_id = any (species_ids))
  order by r.location_public operator(extensions.<->) origin.point
  limit least(greatest(coalesce(max_rows, 50), 1), 200);
$$;

grant execute on function public.reports_in_bbox(double precision, double precision, double precision, double precision, text[], smallint[], integer) to anon, authenticated;
grant execute on function public.reports_near(double precision, double precision, double precision, text[], smallint[], integer) to anon, authenticated;
